name: Robot Framework Automation

on:
  push:
    branches:
      - main

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        robot --outputdir results/ tests/

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: results/
