name: Robot Framework Automation

on:
  push:
    branches:
      - main

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '113.0.5672.63'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        chromedriver --url-base=/wd/hub &
        robot -d Result/ -V ./resource/python/root.py tests/

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: Result/
