name: Robot Framework Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install webdrivermanager

    - name: Configurar o ChromeDriver
      run: |
        webdrivermanager chrome --linkpath /usr/local/bin

    - name: Run Robot Framework tests
      run: |
        chromedriver --url-base=/wd/hub &
        robot -d Result/ -V ./resource/python/root.py tests/

    - name: Publish test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: /home/runner/work/testeVerity/testeVerity/Result/
